import type { Item } from '../types';

// 시작 아이템들 - 12개의 기본 원소
export const BASE_ITEMS: Item[] = [
  {
    id: 'water',
    name: '물',
    emoji: '💧',
    type: 'material',
    rarity: 'common',
    tags: ['water', 'liquid', 'cold'],
    description: '가장 기본적인 원소. 모든 생명의 근원',
    discovered: true,
  },
  {
    id: 'fire',
    name: '불',
    emoji: '🔥',
    type: 'material',
    rarity: 'common',
    tags: ['fire', 'hot', 'energy'],
    description: '뜨겁고 강력한 원소',
    discovered: true,
  },
  {
    id: 'earth',
    name: '흙',
    emoji: '🪨',
    type: 'material',
    rarity: 'common',
    tags: ['earth', 'solid', 'heavy'],
    description: '단단하고 무거운 원소',
    discovered: true,
  },
  {
    id: 'wind',
    name: '바람',
    emoji: '💨',
    type: 'material',
    rarity: 'common',
    tags: ['wind', 'air', 'fast', 'light'],
    description: '가볍고 빠른 원소',
    discovered: true,
  },
  {
    id: 'light',
    name: '빛',
    emoji: '✨',
    type: 'material',
    rarity: 'common',
    tags: ['light', 'holy', 'pure'],
    description: '신성하고 순수한 원소',
    discovered: true,
  },
  {
    id: 'dark',
    name: '어둠',
    emoji: '🌑',
    type: 'material',
    rarity: 'common',
    tags: ['dark', 'cursed', 'evil'],
    description: '저주받은 사악한 원소',
    discovered: true,
  },
  {
    id: 'metal',
    name: '철',
    emoji: '⚙️',
    type: 'material',
    rarity: 'common',
    tags: ['metal', 'iron', 'solid', 'sharp'],
    description: '검을 만드는 기본 재료',
    discovered: true,
  },
  {
    id: 'wood',
    name: '나무',
    emoji: '🪵',
    type: 'material',
    rarity: 'common',
    tags: ['wood', 'nature', 'light'],
    description: '자연의 기운이 담긴 재료',
    discovered: true,
  },
  {
    id: 'stone',
    name: '돌',
    emoji: '🗿',
    type: 'material',
    rarity: 'common',
    tags: ['stone', 'solid', 'heavy', 'dull'],
    description: '단단하지만 무딘 재료',
    discovered: true,
  },
  {
    id: 'ice',
    name: '얼음',
    emoji: '🧊',
    type: 'material',
    rarity: 'common',
    tags: ['ice', 'cold', 'water', 'freeze'],
    description: '얼어붙은 차가운 원소',
    discovered: true,
  },
  {
    id: 'lightning',
    name: '번개',
    emoji: '⚡',
    type: 'material',
    rarity: 'common',
    tags: ['lightning', 'electric', 'fast', 'energy'],
    description: '빠르고 강력한 전기 원소',
    discovered: true,
  },
  {
    id: 'poison',
    name: '독',
    emoji: '☠️',
    type: 'material',
    rarity: 'common',
    tags: ['poison', 'toxic', 'evil', 'green'],
    description: '치명적인 독성 원소',
    discovered: true,
  },
];

// 발견 가능한 총 아이템 수 (기본 + 조합 가능한 모든 아이템)
// 실제로는 수천 개가 가능하지만, 유의미한 발견 목표를 위해
export const TOTAL_DISCOVERABLE_ITEMS = 500;
