import { Item } from './types';

// 아이템 데이터
export const ITEMS: Item[] = [
  // ===== 🍙 삼각김밥 / 주먹밥 =====
  {
    id: 'riceball-tuna',
    name: '참치마요 삼각김밥',
    category: 'riceball',
    emoji: '🍙',
    calories: 250,
    protein: 6,
    sodium: 500,
    sugar: 3,
    vitaminC: 0,
    fiber: 1,
    expiryDays: 3,
  },
  {
    id: 'riceball-kimchi',
    name: '김치 주먹밥',
    category: 'riceball',
    emoji: '🍙',
    calories: 230,
    protein: 5,
    sodium: 600,
    sugar: 2,
    vitaminC: 5,
    fiber: 2,
    expiryDays: 3,
  },
  {
    id: 'riceball-spam',
    name: '스팸 삼각김밥',
    category: 'riceball',
    emoji: '🍙',
    calories: 280,
    protein: 7,
    sodium: 700,
    sugar: 3,
    vitaminC: 0,
    fiber: 1,
    expiryDays: 3,
  },
  {
    id: 'riceball-bulgogi',
    name: '불고기 삼각김밥',
    category: 'riceball',
    emoji: '🍙',
    calories: 260,
    protein: 8,
    sodium: 550,
    sugar: 4,
    vitaminC: 0,
    fiber: 1,
    expiryDays: 3,
  },
  {
    id: 'riceball-chicken',
    name: '치킨마요 삼각김밥',
    category: 'riceball',
    emoji: '🍙',
    calories: 270,
    protein: 9,
    sodium: 580,
    sugar: 3,
    vitaminC: 0,
    fiber: 1,
    expiryDays: 3,
  },

  // ===== 🍜 라면 / 컵라면 =====
  {
    id: 'ramen-shin',
    name: '신라면',
    category: 'ramen',
    emoji: '🍜',
    calories: 500,
    protein: 10,
    sodium: 1790,
    sugar: 5,
    vitaminC: 0,
    fiber: 3,
    description: '매운맛의 정석',
  },
  {
    id: 'ramen-jin',
    name: '진라면',
    category: 'ramen',
    emoji: '🍜',
    calories: 480,
    protein: 9,
    sodium: 1600,
    sugar: 4,
    vitaminC: 0,
    fiber: 3,
  },
  {
    id: 'ramen-buldak',
    name: '불닭볶음면',
    category: 'ramen',
    emoji: '🍜',
    calories: 530,
    protein: 11,
    sodium: 1210,
    sugar: 10,
    vitaminC: 0,
    fiber: 2,
    description: '스트레스 해소용',
  },
  {
    id: 'ramen-neoguri',
    name: '너구리',
    category: 'ramen',
    emoji: '🍜',
    calories: 500,
    protein: 10,
    sodium: 1640,
    sugar: 5,
    vitaminC: 0,
    fiber: 4,
  },
  {
    id: 'ramen-ansungtang',
    name: '안성탕면',
    category: 'ramen',
    emoji: '🍜',
    calories: 490,
    protein: 10,
    sodium: 1380,
    sugar: 4,
    vitaminC: 0,
    fiber: 3,
  },
  {
    id: 'ramen-cup',
    name: '컵라면',
    category: 'ramen',
    emoji: '🥤',
    calories: 350,
    protein: 7,
    sodium: 1100,
    sugar: 4,
    vitaminC: 0,
    fiber: 2,
    description: '조리 간편',
  },

  // ===== 🍱 도시락 / 즉석식품 =====
  {
    id: 'lunchbox-kimbap',
    name: '김밥',
    category: 'lunchbox',
    emoji: '🍱',
    calories: 450,
    protein: 12,
    sodium: 800,
    sugar: 6,
    vitaminC: 10,
    fiber: 4,
    expiryDays: 2,
    description: '야채 포함!',
  },
  {
    id: 'lunchbox-chicken',
    name: '치킨 도시락',
    category: 'lunchbox',
    emoji: '🍱',
    calories: 750,
    protein: 25,
    sodium: 1200,
    sugar: 8,
    vitaminC: 5,
    fiber: 3,
    expiryDays: 2,
  },
  {
    id: 'lunchbox-pork',
    name: '돈까스 도시락',
    category: 'lunchbox',
    emoji: '🍱',
    calories: 800,
    protein: 22,
    sodium: 1300,
    sugar: 10,
    vitaminC: 5,
    fiber: 3,
    expiryDays: 2,
  },
  {
    id: 'lunchbox-sandwich',
    name: '샌드위치',
    category: 'lunchbox',
    emoji: '🥪',
    calories: 350,
    protein: 15,
    sodium: 600,
    sugar: 5,
    vitaminC: 8,
    fiber: 3,
    expiryDays: 2,
    description: '단백질 양호',
  },
  {
    id: 'lunchbox-burger',
    name: '햄버거',
    category: 'lunchbox',
    emoji: '🍔',
    calories: 550,
    protein: 20,
    sodium: 900,
    sugar: 8,
    vitaminC: 3,
    fiber: 2,
    expiryDays: 2,
  },

  // ===== 🍫 과자 / 스낵 =====
  {
    id: 'snack-choco',
    name: '초코파이',
    category: 'snack',
    emoji: '🍫',
    calories: 180,
    protein: 2,
    sodium: 100,
    sugar: 18,
    vitaminC: 0,
    fiber: 1,
  },
  {
    id: 'snack-shrimp',
    name: '새우깡',
    category: 'snack',
    emoji: '🦐',
    calories: 230,
    protein: 3,
    sodium: 350,
    sugar: 2,
    vitaminC: 0,
    fiber: 1,
  },
  {
    id: 'snack-yes',
    name: '오예스',
    category: 'snack',
    emoji: '🍪',
    calories: 500,
    protein: 5,
    sodium: 200,
    sugar: 35,
    vitaminC: 0,
    fiber: 2,
    description: '칼로리 폭탄',
  },
  {
    id: 'snack-potato',
    name: '포카칩',
    category: 'snack',
    emoji: '🥔',
    calories: 270,
    protein: 3,
    sodium: 300,
    sugar: 1,
    vitaminC: 5,
    fiber: 2,
  },
  {
    id: 'snack-pepero',
    name: '빼빼로',
    category: 'snack',
    emoji: '🍫',
    calories: 240,
    protein: 3,
    sodium: 80,
    sugar: 20,
    vitaminC: 0,
    fiber: 1,
  },
  {
    id: 'snack-honey',
    name: '허니버터칩',
    category: 'snack',
    emoji: '🍯',
    calories: 280,
    protein: 3,
    sodium: 250,
    sugar: 15,
    vitaminC: 0,
    fiber: 2,
  },

  // ===== 🍪 빵 / 베이커리 =====
  {
    id: 'bread-cream',
    name: '크림빵',
    category: 'bread',
    emoji: '🍞',
    calories: 320,
    protein: 6,
    sodium: 200,
    sugar: 25,
    vitaminC: 0,
    fiber: 2,
    expiryDays: 5,
  },
  {
    id: 'bread-red-bean',
    name: '단팥빵',
    category: 'bread',
    emoji: '🍞',
    calories: 300,
    protein: 7,
    sodium: 180,
    sugar: 22,
    vitaminC: 0,
    fiber: 3,
    expiryDays: 5,
  },
  {
    id: 'bread-soboro',
    name: '소보로빵',
    category: 'bread',
    emoji: '🍞',
    calories: 350,
    protein: 6,
    sodium: 220,
    sugar: 28,
    vitaminC: 0,
    fiber: 2,
    expiryDays: 5,
  },
  {
    id: 'bread-morning',
    name: '모닝빵',
    category: 'bread',
    emoji: '🥐',
    calories: 280,
    protein: 5,
    sodium: 200,
    sugar: 15,
    vitaminC: 0,
    fiber: 2,
    expiryDays: 5,
  },
  {
    id: 'bread-sliced',
    name: '식빵',
    category: 'bread',
    emoji: '🍞',
    calories: 250,
    protein: 8,
    sodium: 300,
    sugar: 5,
    vitaminC: 0,
    fiber: 3,
    expiryDays: 5,
  },

  // ===== 🥛 유제품 =====
  {
    id: 'dairy-banana',
    name: '바나나우유',
    category: 'dairy',
    emoji: '🥛',
    calories: 200,
    protein: 6,
    sodium: 100,
    sugar: 28,
    vitaminC: 2,
    fiber: 1,
    expiryDays: 7,
    description: '힐링 음료',
  },
  {
    id: 'dairy-strawberry',
    name: '딸기우유',
    category: 'dairy',
    emoji: '🥛',
    calories: 210,
    protein: 6,
    sodium: 100,
    sugar: 30,
    vitaminC: 15,
    fiber: 1,
    expiryDays: 7,
  },
  {
    id: 'dairy-chocolate',
    name: '초코우유',
    category: 'dairy',
    emoji: '🥛',
    calories: 220,
    protein: 7,
    sodium: 120,
    sugar: 32,
    vitaminC: 1,
    fiber: 1,
    expiryDays: 7,
  },
  {
    id: 'dairy-yogurt',
    name: '요거트',
    category: 'dairy',
    emoji: '🥄',
    calories: 100,
    protein: 4,
    sodium: 50,
    sugar: 12,
    vitaminC: 2,
    fiber: 0,
    expiryDays: 7,
    description: '유산균 → 건강 +5%',
  },
  {
    id: 'dairy-cheese',
    name: '치즈',
    category: 'dairy',
    emoji: '🧀',
    calories: 350,
    protein: 25,
    sodium: 600,
    sugar: 1,
    vitaminC: 0,
    fiber: 0,
    expiryDays: 7,
  },

  // ===== 🥫 통조림 =====
  {
    id: 'canned-tuna',
    name: '참치캔',
    category: 'canned',
    emoji: '🥫',
    calories: 120,
    protein: 25,
    sodium: 400,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    description: '단백질 폭탄, 오래 보관',
  },
  {
    id: 'canned-spam',
    name: '스팸',
    category: 'canned',
    emoji: '🥫',
    calories: 310,
    protein: 13,
    sodium: 750,
    sugar: 1,
    vitaminC: 0,
    fiber: 0,
    description: '칼로리 높음',
  },
  {
    id: 'canned-fruit',
    name: '과일 통조림',
    category: 'canned',
    emoji: '🥫',
    calories: 80,
    protein: 1,
    sodium: 10,
    sugar: 18,
    vitaminC: 20,
    fiber: 2,
    description: '비타민 보충',
  },
  {
    id: 'canned-beans',
    name: '콩 통조림',
    category: 'canned',
    emoji: '🥫',
    calories: 130,
    protein: 8,
    sodium: 300,
    sugar: 2,
    vitaminC: 5,
    fiber: 6,
  },

  // ===== 🍎 과일 / 야채 =====
  {
    id: 'fruit-banana',
    name: '바나나',
    category: 'fruit',
    emoji: '🍌',
    calories: 90,
    protein: 1,
    sodium: 1,
    sugar: 12,
    vitaminC: 10,
    fiber: 3,
    expiryDays: 5,
    description: '칼륨 함유',
  },
  {
    id: 'fruit-apple',
    name: '사과',
    category: 'fruit',
    emoji: '🍎',
    calories: 50,
    protein: 0,
    sodium: 2,
    sugar: 10,
    vitaminC: 5,
    fiber: 2,
    expiryDays: 5,
  },
  {
    id: 'fruit-tomato',
    name: '방울토마토',
    category: 'fruit',
    emoji: '🍅',
    calories: 20,
    protein: 1,
    sodium: 5,
    sugar: 3,
    vitaminC: 15,
    fiber: 1,
    expiryDays: 3,
  },
  {
    id: 'fruit-salad',
    name: '샐러드',
    category: 'fruit',
    emoji: '🥗',
    calories: 50,
    protein: 2,
    sodium: 100,
    sugar: 3,
    vitaminC: 20,
    fiber: 3,
    expiryDays: 3,
  },

  // ===== 🍬 사탕 / 초콜릿 =====
  {
    id: 'candy-sour',
    name: '새콤달콤',
    category: 'candy',
    emoji: '🍬',
    calories: 50,
    protein: 0,
    sodium: 5,
    sugar: 12,
    vitaminC: 5,
    fiber: 0,
  },
  {
    id: 'candy-mychew',
    name: '마이쮸',
    category: 'candy',
    emoji: '🍬',
    calories: 60,
    protein: 0,
    sodium: 10,
    sugar: 14,
    vitaminC: 0,
    fiber: 0,
  },
  {
    id: 'candy-chocobar',
    name: '초코바',
    category: 'candy',
    emoji: '🍫',
    calories: 250,
    protein: 3,
    sodium: 50,
    sugar: 28,
    vitaminC: 0,
    fiber: 1,
  },
  {
    id: 'candy-jelly',
    name: '젤리',
    category: 'candy',
    emoji: '🍬',
    calories: 70,
    protein: 0,
    sodium: 15,
    sugar: 16,
    vitaminC: 10,
    fiber: 0,
  },

  // ===== ☕️ 음료 / 카페인 =====
  {
    id: 'drink-coffee',
    name: '커피',
    category: 'drink',
    emoji: '☕️',
    calories: 5,
    protein: 0,
    sodium: 5,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    caffeine: 80,
    description: '정신력 +10',
  },
  {
    id: 'drink-energy',
    name: '에너지드링크',
    category: 'drink',
    emoji: '🥤',
    calories: 110,
    protein: 0,
    sodium: 200,
    sugar: 27,
    vitaminC: 0,
    fiber: 0,
    caffeine: 80,
    description: '카페인 과다 주의',
  },
  {
    id: 'drink-ion',
    name: '이온음료',
    category: 'drink',
    emoji: '🥤',
    calories: 80,
    protein: 0,
    sodium: 100,
    sugar: 19,
    vitaminC: 0,
    fiber: 0,
    description: '전해질 보충',
  },
  {
    id: 'drink-soda',
    name: '탄산음료',
    category: 'drink',
    emoji: '🥤',
    calories: 140,
    protein: 0,
    sodium: 40,
    sugar: 35,
    vitaminC: 0,
    fiber: 0,
  },
  {
    id: 'drink-vitamin',
    name: '비타민 음료',
    category: 'drink',
    emoji: '🧃',
    calories: 100,
    protein: 0,
    sodium: 50,
    sugar: 23,
    vitaminC: 100,
    fiber: 0,
    description: '비타민C 충분',
  },

  // ===== 🍺 주류 =====
  {
    id: 'alcohol-soju',
    name: '소주',
    category: 'alcohol',
    emoji: '🍶',
    calories: 540,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    alcohol: 16.9,
    description: '스트레스 -50%, 판단력 -30%',
  },
  {
    id: 'alcohol-beer',
    name: '맥주',
    category: 'alcohol',
    emoji: '🍺',
    calories: 150,
    protein: 1,
    sodium: 10,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    alcohol: 4.5,
  },

  // ===== 💊 건강식품 =====
  {
    id: 'supplement-vitamin',
    name: '비타민제',
    category: 'supplement',
    emoji: '💊',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 1000,
    fiber: 0,
    description: '비타민 결핍 방지',
  },
  {
    id: 'supplement-nutrient',
    name: '영양제',
    category: 'supplement',
    emoji: '💊',
    calories: 10,
    protein: 0,
    sodium: 5,
    sugar: 0,
    vitaminC: 50,
    fiber: 0,
  },
  {
    id: 'supplement-protein',
    name: '단백질바',
    category: 'supplement',
    emoji: '🍫',
    calories: 200,
    protein: 20,
    sodium: 150,
    sugar: 5,
    vitaminC: 0,
    fiber: 3,
    description: '단백질 보충',
  },

  // ===== 🔧 잡화 (함정 아이템들) =====
  {
    id: 'misc-hammer',
    name: '망치',
    category: 'misc',
    emoji: '🔨',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'penalty',
      days: -30,
      message: '흥분한 당신은 망치를 휘둘렀지만, 강화유리는 끄떡없었습니다. 대신 반동으로 망치가 발등에 떨어졌습니다. **발등 골절** 💀',
    },
  },
  {
    id: 'misc-ladder',
    name: '사다리',
    category: 'misc',
    emoji: '🪜',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'penalty',
      days: -14,
      message: '사다리를 타고 올라갔지만, 환풍구는 너무 좁았습니다. 내려오다가 **발을 헛디뎌 낙상**. 허리 부상으로 2주간 누워있었습니다. 💀',
    },
  },
  {
    id: 'misc-knife',
    name: '칼 (커터칼)',
    category: 'misc',
    emoji: '🔪',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'penalty',
      days: -7,
      message: '통조림을 따다가 **손을 베었습니다**. 소독약은 없고, 감염 위험이 높아졌습니다.',
    },
  },
  {
    id: 'misc-candle',
    name: '양초 / 라이터',
    category: 'misc',
    emoji: '🕯️',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'instant_death',
      days: 0,
      message: '심심해서 양초를 켜고 놀다가 **화재 발생**. 편의점이 불탔습니다. 🔥🔥🔥',
    },
  },
  {
    id: 'misc-detergent',
    name: '세제 / 표백제',
    category: 'misc',
    emoji: '🧴',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'penalty',
      days: -10,
      message: '심심해서 세제로 바닥을 닦았습니다. 미끄러져 **뒤통수 강타**. 뇌진탕으로 고생했습니다.',
    },
  },
  {
    id: 'misc-battery',
    name: '건전지',
    category: 'misc',
    emoji: '🔋',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'penalty',
      days: 0,
      message: '건전지로는 휴대폰 충전이 안 됩니다. **쓸모없음**.',
    },
  },
  {
    id: 'misc-newspaper',
    name: '신문 / 잡지',
    category: 'misc',
    emoji: '📰',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'bonus',
      days: 2,
      message: '시간 때우기 좋았습니다. **정신력 +5%**',
    },
  },
  {
    id: 'misc-boardgame',
    name: '보드게임 / 카드',
    category: 'misc',
    emoji: '🎲',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'penalty',
      days: -3,
      message: '혼자 카드놀이를 하다가 **더 우울해졌습니다**. 정신력 약화.',
    },
  },
  {
    id: 'misc-tissue',
    name: '휴지 / 물티슈',
    category: 'misc',
    emoji: '🧻',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'bonus',
      days: 5,
      message: '위생을 잘 관리했습니다. **건강 +10%**',
    },
  },
  {
    id: 'misc-firstaid',
    name: '구급상자',
    category: 'misc',
    emoji: '💊',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'bonus',
      days: 10,
      message: '부상 위험 감소. **생존력 +20%**',
    },
  },
  {
    id: 'misc-flashlight',
    name: '손전등',
    category: 'misc',
    emoji: '🔦',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'bonus',
      days: 3,
      message: '전기는 안 나갔지만, 밤에 안정감을 줬습니다. **정신력 +5%**',
    },
  },
  {
    id: 'misc-charger',
    name: '충전기',
    category: 'misc',
    emoji: '📱',
    calories: 0,
    protein: 0,
    sodium: 0,
    sugar: 0,
    vitaminC: 0,
    fiber: 0,
    isTrap: true,
    trapEffect: {
      type: 'bonus',
      days: 5,
      message: '휴대폰으로 시간을 보낼 수 있었습니다. (배터리는 다행히 있음) 스트레스 감소.',
    },
  },
];

// 카테고리 정보
export const CATEGORY_INFO: Record<string, { name: string; emoji: string; description: string }> = {
  riceball: { name: '삼각김밥 / 주먹밥', emoji: '🍙', description: '유통기한 3일' },
  ramen: { name: '라면 / 컵라면', emoji: '🍜', description: '나트륨 폭탄' },
  lunchbox: { name: '도시락 / 즉석식품', emoji: '🍱', description: '균형잡힌 영양' },
  snack: { name: '과자 / 스낵', emoji: '🍫', description: '장기 보관 가능' },
  bread: { name: '빵 / 베이커리', emoji: '🍞', description: '유통기한 5일' },
  dairy: { name: '유제품', emoji: '🥛', description: '단백질, 칼슘' },
  canned: { name: '통조림', emoji: '🥫', description: '장기 보관 최강!' },
  fruit: { name: '과일 / 야채', emoji: '🍎', description: '비타민 보충' },
  candy: { name: '사탕 / 초콜릿', emoji: '🍬', description: '즉각 에너지' },
  drink: { name: '음료 / 카페인', emoji: '☕️', description: '수분 및 에너지' },
  alcohol: { name: '주류', emoji: '🍺', description: '⚠️ 위험한 선택' },
  supplement: { name: '건강식품', emoji: '💊', description: '생존력 증가' },
  misc: { name: '잡화', emoji: '🔧', description: '⚠️ 신중하게!' },
};

// 로딩 메시지
export const LOADING_MESSAGES = [
  '칼로리 계산 중...',
  '나트륨 농도 측정 중...',
  '단백질 함량 분석 중...',
  '비타민 수치 확인 중...',
  '생존 가능성 예측 중...',
  '사망 원인 분석 중...',
  '함정 아이템 탐지 중...',
  '영양 균형 계산 중...',
  '당분 과다 체크 중...',
  '최종 결과 도출 중...',
];
